# Generated by Django 5.2.7 on 2025-10-13 21:42

import processador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=processador.models.upload_para_path)),
                ('resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
